# Generated by Django 3.1.7 on 2021-03-05 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=300)),
                ('category_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_accounting.categoryproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_warehouse', models.CharField(max_length=300)),
                ('receipt_date', models.DateField()),
                ('count_product', models.IntegerField()),
                ('products', models.ManyToManyField(to='sales_accounting.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_shop', models.CharField(max_length=400)),
                ('price_product', models.FloatField()),
                ('count', models.IntegerField()),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_accounting.product')),
                ('warehouses', models.ManyToManyField(to='sales_accounting.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='SalesAccounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_accounting.categoryproduct')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_accounting.product')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_accounting.shop')),
                ('warehouses_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_accounting.warehouse')),
            ],
        ),
    ]
