# Generated by Django 3.1.7 on 2021-03-08 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={'verbose_name': 'Category Product', 'verbose_name_plural': 'Category Products'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='salesaccounting',
            options={'verbose_name': 'Sales Accounting', 'verbose_name_plural': 'Sales Accounting'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['receipt_date'], 'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
    ]
